# Generated by Django 5.2.3 on 2025-06-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('scope', models.TextField(blank=True, null=True)),
                ('design', models.TextField(blank=True, null=True)),
                ('literature', models.TextField(blank=True, null=True)),
                ('analysis', models.TextField(blank=True, null=True)),
                ('discussion', models.TextField(blank=True, null=True)),
                ('ethics', models.TextField(blank=True, null=True)),
                ('references', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
